### ISSUE TITLE
Instructions for using MEW to interact with the bridge don't seem to work 

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/Public_Test_Bridge_Tools#16]
Nixik_Pixik in Discord was trying to folllow the instructions for interacting with the bridge without using Console and Metamask at: https://github.com/vegaprotocol/Public_Test_Bridge_Tools/blob/master/docs/mew.md

They found a broken link to: https://raw.githubusercontent.com/vegaprotocol/Public_Test_Bridge_Tools/master/bridge/Vega_Bridge_ERC20_abi.json

Discord chat link: https://discord.com/channels/720571334798737489/732949310198644897/824282901625045042

We should review and update these instructions, ensure they are working.

**Comment by cdm** [comment]
I've fixed the broken link, and updated it to match the latest bridge ABI json

**Comment by cdm** [comment]
@C0deMunk33 please check and verify my latest change on this file https://github.com/vegaprotocol/Public_Test_Bridge_Tools/blob/master/docs/mew.md

If correct please close this issue 👍

**Comment by C0deMunk33** [comment]
there's actually a couple broken links. working on them now.

**Comment by cdm** [comment]
I think this has now been resolved by @C0deMunk33, closing issue.
