### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/Public_Test_Bridge_Tools#7]
- [x] remove photo of metamask with assets
- [x] add a tip that people can check on their transactions using etherscan

**Comment by edd** [comment]
@candida-d Are these covered? I think point 2 isn't yet.

**Comment by candida-d** [comment]
@edd This PR should cover point 2 https://github.com/vegaprotocol/Public_Test_Bridge_Tools/pull/11
